### ISSUE TITLE
Can't parse simple case

### ISSUE THREAD

**Issue by Stargateur** [RReverser/serde-xml-rs#107]
```rust
use serde::Deserialize;
use serde_xml_rs::from_str;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Error {
    code: u32,
    message: String,
}

#[derive(Debug, Deserialize)]
struct Item {
}

#[derive(Debug, Deserialize)]
enum DataSet {
    Item(Vec<Item>),
    Error(Error),
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Document {
    data_set: DataSet,
}



fn main() {
    let error = r#"
    <DataSet>
        <Error>
            <Code>0</Code>
            <Message>error</Message>
        </Error>
    </DataSet>
    "#;

    let dataset: Document = from_str(error).unwrap();
    println!("{:#?}", dataset);

    let items = r#"
    <DataSet>
        <Item>..</Item>
        <Item>..</Item>
    </DataSet>
"#;

    let dataset: Document = from_str(items).unwrap();
    println!("{:#?}", dataset);
}
```

with

```toml
[package]
name = "playground"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde-xml-rs = "0.3"
```
fail with:
```none
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Custom("missing field `DataSet`"), State { next_error: None, backtrace: None })', src\libcore\result.rs:999:5
```

I believe it the same issue than https://github.com/RReverser/serde-xml-rs/issues/103. But can't know for sure.

If I do `let dataset: DataSet = from_str(error).unwrap();`

```none
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Custom("unknown variant `DataSet`, expected `Item` or `Error`"), State { next_error: None, backtrace: None })', src\libcore\result.rs:999:5
```

Note that doing `let dataset: serde_json::Value = from_str(error).unwrap();` give:

```none
Object(
    {
        "Error": Object(
            {
                "Code": Object(
                    {
                        "$value": String(
                            "0",
                        ),
                    },
                ),
                "Message": Object(
                    {
                        "$value": String(
                            "error",
                        ),
                    },
                ),
            },
        ),
    },
)
```

Where is `DataSet` ?

**Comment by punkstarman** [comment]
The document can't be deserialized because the root tag is missing. The error message can be misleading because the name of the root tag is never checked by the deserializer. The following code works.

```rust
fn main() {
    let error = r#"
    <Document>
        <DataSet>
            <Error>
                <Code>0</Code>
                <Message>error</Message>
            </Error>
        </DataSet>
    </Document>"#;

    let dataset: Document = from_str(error).unwrap();
    println!("{:#?}", dataset);

    let items = r#"
    <Document>
        <DataSet>
            <Item>..</Item>
            <Item>..</Item>
        </DataSet>
    </Document>"#;

    let dataset: Document = from_str(items).unwrap();
    println!("{:#?}", dataset);
}
```

This is in line with the documentation (see example in [README](https://github.com/RReverser/serde-xml-rs/blob/master/README.md))


Concerning how the document is parsed to a JSON value, JSON doesn't tag the root node, whereas XML does. When translating XML to JSON, one must decide what to do with the name of the root tag. This project decides to drop it.

**Comment by Stargateur** [comment]
Oh I see my bad, I don't use xml.

But the exemple, use `Project` if the first get ignored why `let dataset: DataSet = from_str(error).unwrap();` doesn't work too ? This was the first thing I did.

**Comment by punkstarman** [comment]
The root tag isn't ignored. It must be there for the rest of the document to be deserialized. The name of the root tag isn't checked.

For instance, the following code also works.

```rust
fn main() {
    let error = r#"
    <Pikachu>
        <DataSet>
            <Error>
                <Code>0</Code>
                <Message>error</Message>
            </Error>
        </DataSet>
    </Pikachu>"#;

    let dataset: Document = from_str(error).unwrap();
    println!("{:#?}", dataset);

    let items = r#"
    <Pikachu>
        <DataSet>
            <Item>..</Item>
            <Item>..</Item>
        </DataSet>
    </Pikachu>"#;

    let dataset: Document = from_str(items).unwrap();
    println!("{:#?}", dataset);
}
```

**Comment by Stargateur** [comment]
Yes I understood that but why this doesn't work:

```rust
use serde::Deserialize;
use serde_xml_rs::from_str;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Error {
    code: u32,
    message: String,
}

#[derive(Debug, Deserialize)]
struct Item {
}

#[derive(Debug, Deserialize)]
enum DataSet {
    Item(Vec<Item>),
    Error(Error),
}



fn main() {
    let error = r#"
    <DataSet>
        <Error>
            <Code>0</Code>
            <Message>error</Message>
        </Error>
    </DataSet>
    "#;

    let dataset: DataSet = from_str(error).unwrap();
}
```

```none
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Custom("unknown variant `DataSet`, expected `Item` or `Error`"), State { next_error: None, backtrace: None })', src\libcore\result.rs:999:5
```

Obviously this should work no ?

**Comment by punkstarman** [comment]
Yes, `enum`s are handled differently.

The following works.

```rust
fn main() {
    let error = r#"
            <Error>
                <Code>0</Code>
                <Message>error</Message>
            </Error>"#;

    let dataset: DataSet = from_str(error).unwrap();
    println!("{:#?}", dataset);
}
```
